2020-06-12 19:44:48,810 INFO: Qaari startup [in /home/hp/Qaari/app/__init__.py:43]
2020-06-15 15:12:07,772 INFO: Qaari startup [in /home/hp/Qaari/app/__init__.py:43]
2020-06-15 15:23:59,302 INFO: Qaari startup [in /home/hp/Qaari/app/__init__.py:43]
2020-06-15 15:24:26,146 ERROR: Exception on /edit_profile [GET] [in /home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hp/Qaari/app/routes.py", line 70, in edit_profile
    form = EditProfileForm(current_user.username)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/home/hp/Qaari/app/forms.py", line 36, in __init__
    super(EditProfileForm, self).__inti__(*args, **kwargs)
AttributeError: 'super' object has no attribute '__inti__'
2020-06-15 15:29:31,883 INFO: Qaari startup [in /home/hp/Qaari/app/__init__.py:43]
2020-06-15 15:29:35,405 ERROR: Exception on /edit_profile [GET] [in /home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hp/Qaari/app/routes.py", line 70, in edit_profile
    form = EditProfileForm(current_user.username)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/home/hp/Qaari/app/forms.py", line 36, in __init__
    super(EditProfileForm, self).__intit__(*args, **kwargs)
AttributeError: 'super' object has no attribute '__intit__'
2020-06-15 15:29:36,432 ERROR: Exception on /edit_profile [GET] [in /home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hp/Qaari/app/routes.py", line 70, in edit_profile
    form = EditProfileForm(current_user.username)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/home/hp/Qaari/app/forms.py", line 36, in __init__
    super(EditProfileForm, self).__intit__(*args, **kwargs)
AttributeError: 'super' object has no attribute '__intit__'
2020-06-15 15:29:39,800 ERROR: Exception on /edit_profile [GET] [in /home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hp/Qaari/app/routes.py", line 70, in edit_profile
    form = EditProfileForm(current_user.username)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/home/hp/Qaari/app/forms.py", line 36, in __init__
    super(EditProfileForm, self).__intit__(*args, **kwargs)
AttributeError: 'super' object has no attribute '__intit__'
2020-06-15 15:29:50,717 ERROR: Exception on /edit_profile [GET] [in /home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hp/Qaari/app/routes.py", line 70, in edit_profile
    form = EditProfileForm(current_user.username)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/home/hp/Qaari/app/forms.py", line 36, in __init__
    super(EditProfileForm, self).__intit__(*args, **kwargs)
AttributeError: 'super' object has no attribute '__intit__'
2020-06-15 15:30:21,328 ERROR: Exception on /edit_profile [GET] [in /home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hp/Qaari/app/routes.py", line 70, in edit_profile
    form = EditProfileForm(current_user.username)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/home/hp/Qaari/app/forms.py", line 36, in __init__
    super(EditProfileForm, self).__init__(*args, **kwargs)
AttributeError: 'super' object has no attribute '__intit__'
