2020-06-15 18:50:22,465 ERROR: Exception on /index [GET] [in /home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/hp/Qaari/app/routes.py", line 28, in index
    return render_template('index.html', title="Home", user=user, posts=posts)
UnboundLocalError: local variable 'posts' referenced before assignment
2020-06-15 18:50:23,857 ERROR: Exception on /index [GET] [in /home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/hp/Qaari/app/routes.py", line 28, in index
    return render_template('index.html', title="Home", user=user, posts=posts)
UnboundLocalError: local variable 'posts' referenced before assignment
2020-06-15 18:50:25,154 ERROR: Exception on /index [GET] [in /home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/hp/Qaari/app/routes.py", line 28, in index
    return render_template('index.html', title="Home", user=user, posts=posts)
UnboundLocalError: local variable 'posts' referenced before assignment
2020-06-15 18:51:26,396 ERROR: Exception on /index [GET] [in /home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/hp/Qaari/app/routes.py", line 28, in index
    return render_template('index.html', title="Home", user=user, posts=posts)
UnboundLocalError: local variable 'posts' referenced before assignment
2020-06-15 18:54:55,256 ERROR: Exception on /index [GET] [in /home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/hp/Qaari/app/routes.py", line 28, in index
    return render_template('index.html', title="Home", user=user, posts=posts)
UnboundLocalError: local variable 'posts' referenced before assignment
2020-06-15 18:54:56,963 ERROR: Exception on /index [GET] [in /home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/hp/Qaari/app/routes.py", line 28, in index
    return render_template('index.html', title="Home", user=user, posts=posts)
UnboundLocalError: local variable 'posts' referenced before assignment
2020-06-15 18:54:57,948 ERROR: Exception on /index [GET] [in /home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/hp/Qaari/app/routes.py", line 28, in index
    return render_template('index.html', title="Home", user=user, posts=posts)
UnboundLocalError: local variable 'posts' referenced before assignment
