2020-06-16 22:08:34,393 ERROR: Exception on /user/harami [GET] [in /home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/hp/Qaari/app/routes.py", line 90, in user
    next_url=next_url, prev_url=prev_url, form=form)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/hp/Qaari/app/templates/user.html", line 40, in template
    {% endif %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endif'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2020-06-16 22:09:40,508 ERROR: Exception on /user/harami [GET] [in /home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/hp/Qaari/app/routes.py", line 90, in user
    next_url=next_url, prev_url=prev_url, form=form)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/hp/Qaari/app/templates/user.html", line 40, in template
    {% endif %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endif'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2020-06-16 22:09:42,609 ERROR: Exception on /user/harami [GET] [in /home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/hp/Qaari/app/routes.py", line 90, in user
    next_url=next_url, prev_url=prev_url, form=form)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/hp/.virtual_envs/Qaari/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/hp/Qaari/app/templates/user.html", line 40, in template
    {% endif %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endif'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2020-06-16 22:11:11,996 INFO: Qaari startup [in /home/hp/Qaari/app/__init__.py:43]
2020-06-16 22:13:15,293 INFO: Qaari startup [in /home/hp/Qaari/app/__init__.py:43]
2020-06-19 15:23:59,123 INFO: Qaari startup [in /home/hp/Qaari/app/__init__.py:45]
